#!/bin/bash
# ==========================================================================
# Subversion Control:
# $Revision$
# $Date$
# ==========================================================================
#
# File     : syn_stn2tft
# Author   : Handsome Huang
# Abstract : Synthesis running script
#
# ==========================================================================
# Modification History:
# Date          By           Changes Description
# ----------------------------------------------------------------------
# 2012/09/01    Handsome     New creation
#
# ==========================================================================

./run_syn -prj stn2tft -trg stn2tft -bom xc3s50a-vq100-4 -mod imp

#./run_syn -prj dps_tmp -trg dps -bom xc3s200a-ft256-5 -mod imp

###./run_syn -prj dps_new -trg dps -bom xc6slx150t-fgg676-3 -mod imp

#./run_syn -prj dps -trg dps -bom xc5vlx110-ff1153-1 -mod imp
#./run_syn -prj s1c17803_icd -trg s1c17803 -bom xc2vp40-fg676-5 -mod imp
