#!/bin/bash
# ==========================================================================
# Subversion Control:
# $Revision$
# $Date$
# ==========================================================================
# File     : qa_monitor
# Author   : Handsome Huang
# Abstract : Simulation running script
#
# ==========================================================================
# Modification History:
# Date        By          Change Description
# ---------------------------------------------------------------------
# 2012/11/07  Handsome    New creation.
#
# ==========================================================================
./run_sim.pl -m mon -t tb_mon_top -c 5000 -p 39_000 -w sscan -d typ 


