file fls17801.elf
target icd usb
load

c17 fls 0x0020000 0x003ffff FLASH_ERASE FLASH_LOAD
c17 fle 0x20000 0 0


# Command file generated by Gnu17 Plug-in for Eclipse
# load debugging information in program
file stn2tft.elf
# set the memory configuration map file to the debugger
c17 rpf stn2tft_gnu17IDE.par
# connect to the debugger with specified mode and port
# target [icd usb | sim]
target icd usb
# load program to memory
load stn2tft.elf
# reset
c17 rst



